DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "sections"
baseURL = "https://andyjones789.github.io/mits-website-prototype/"
buildDrafts = "true"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
staticDir = "static"
theme = "ananke"
title = "My New Hugo Site"
[params]
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
facebook = ""
favicon = ""
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
recent_posts_number = 2
slack = ""
twitter = "https://twitter.com/makeitsimpleuk"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
